// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7kN5NdAqPWdOlMqlF4RDqB0Hrf032a08',
    appId: '1:475510528118:web:f07fc6d9561cfa15ed2757',
    messagingSenderId: '475510528118',
    projectId: 'healthway-a0e87',
    authDomain: 'healthway-a0e87.firebaseapp.com',
    storageBucket: 'healthway-a0e87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKQR47nNS3_AOnPsnaU-Vg7im9OvVhcU',
    appId: '1:475510528118:android:0b34371d3eb0b96eed2757',
    messagingSenderId: '475510528118',
    projectId: 'healthway-a0e87',
    storageBucket: 'healthway-a0e87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2FitPy0l-DAyb4AhHQO6yyQ8sjVmziqI',
    appId: '1:475510528118:ios:84cfb06842fa824ded2757',
    messagingSenderId: '475510528118',
    projectId: 'healthway-a0e87',
    storageBucket: 'healthway-a0e87.firebasestorage.app',
    iosBundleId: 'com.example.healthwayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2FitPy0l-DAyb4AhHQO6yyQ8sjVmziqI',
    appId: '1:475510528118:ios:84cfb06842fa824ded2757',
    messagingSenderId: '475510528118',
    projectId: 'healthway-a0e87',
    storageBucket: 'healthway-a0e87.firebasestorage.app',
    iosBundleId: 'com.example.healthwayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7kN5NdAqPWdOlMqlF4RDqB0Hrf032a08',
    appId: '1:475510528118:web:d09a2a5cf4176c26ed2757',
    messagingSenderId: '475510528118',
    projectId: 'healthway-a0e87',
    authDomain: 'healthway-a0e87.firebaseapp.com',
    storageBucket: 'healthway-a0e87.firebasestorage.app',
  );
}
