# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DEV - Start & Test (API)

on:
  push:
    branches: [ "iury" ]
  pull_request:
    branches: [ "iury" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Create .env file
      working-directory: backend
      run: echo "FIREBASE_CONFIG=${{ secrets.FIREBASE_CONFIG }}" > .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: backend
    - run: npm test
      working-directory: backend
    - run: npm start
      working-directory: backend
